name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: pip install unittest

    - name: Run unit tests
      run: python -m unittest test_main.py

    - name: Run main script
      run: python main.py
